#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y%m%d_%H%M%S)"

PROFILE="${PROFILE:-codex_demos_arc}"
RUNS="${RUNS:-8}"
MAX_LOOPS="${MAX_LOOPS:-220}"
CONSOLE_PROFILE="${CONSOLE_PROFILE:-normal}"
PREP_STARTER_SAVE="${PREP_STARTER_SAVE:-1}"
STARTER_SAVE_SLOT="${STARTER_SAVE_SLOT:-2}"
OUT_DIR_BASE="${OUT_DIR_BASE:-${SCRIPT_DIR}/logs/playtests/codex_demos_arc}"
OUT_DIR="${OUT_DIR:-${OUT_DIR_BASE}/${STAMP}}"
ARCHIVE_RIG_DATA="${ARCHIVE_RIG_DATA:-1}"
STRICT_BIOME_ECONOMY="${STRICT_BIOME_ECONOMY:-1}"
REUSE_LISTENER="${REUSE_LISTENER:-1}"
RESOURCE_MODE="${RESOURCE_MODE:-set}"

mkdir -p "${OUT_DIR_BASE}"

PROFILE="${PROFILE}" \
RUNS="${RUNS}" \
MAX_LOOPS="${MAX_LOOPS}" \
OUT_DIR="${OUT_DIR}" \
CONSOLE_PROFILE="${CONSOLE_PROFILE}" \
PREP_STARTER_SAVE="${PREP_STARTER_SAVE}" \
STARTER_SAVE_SLOT="${STARTER_SAVE_SLOT}" \
ARCHIVE_RIG_DATA="${ARCHIVE_RIG_DATA}" \
STRICT_BIOME_ECONOMY="${STRICT_BIOME_ECONOMY}" \
REUSE_LISTENER="${REUSE_LISTENER}" \
RESOURCE_MODE="${RESOURCE_MODE}" \
"${SCRIPT_DIR}/🧭🥛🧪🚜.sh"
