#!/usr/bin/env bash
set -euo pipefail

# 💾🏷️ - Emoji save alias helper
# Lists and inspects emoji-named save aliases generated by SaveStore.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
XDG_ROOT="${XDG_ROOT:-${PROJECT_ROOT}/.godot}"
APP_NAME="${APPLICATION_NAME:-SpaceWheat - Quantum Farm}"
PRIMARY_SAVE_DIR="${XDG_ROOT}/godot/app_userdata/${APP_NAME}/saves"
FALLBACK_SAVE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/godot/app_userdata/${APP_NAME}/saves"
SAVE_DIR="${PRIMARY_SAVE_DIR}"
if [[ -f "${FALLBACK_SAVE_DIR}/emoji_save_index.json" && ! -f "${PRIMARY_SAVE_DIR}/emoji_save_index.json" ]]; then
  SAVE_DIR="${FALLBACK_SAVE_DIR}"
elif [[ ! -d "${SAVE_DIR}" && -d "${FALLBACK_SAVE_DIR}" ]]; then
  SAVE_DIR="${FALLBACK_SAVE_DIR}"
fi
INDEX_FILE="${SAVE_DIR}/emoji_save_index.json"

usage() {
  cat <<'EOF'
Usage: 🍄/🎛️/💾🏷️.sh [command]

Commands:
  list            List slot -> emoji alias mappings (default)
  slot <n>        Show detailed alias info for slot n
  sidecar <n>     Print sidecar JSON for slot n (if present)
  files           List emoji alias .tres files on disk
  index-path      Print resolved index file path
EOF
}

cmd="${1:-list}"

if [[ "${cmd}" == "index-path" ]]; then
  echo "${INDEX_FILE}"
  exit 0
fi

if [[ ! -f "${INDEX_FILE}" ]]; then
  echo "No emoji save index found: ${INDEX_FILE}"
  exit 1
fi

case "${cmd}" in
  list)
    python3 - "$INDEX_FILE" <<'PY'
import json, sys
path = sys.argv[1]
data = json.load(open(path, encoding="utf-8"))
slots = data.get("slots", {})
if not isinstance(slots, dict) or not slots:
    print("No slot alias metadata in index.")
    raise SystemExit(0)
for key in sorted(slots.keys(), key=lambda s: int(s) if str(s).isdigit() else 999):
    row = slots.get(key, {})
    print(f"slot={key} emoji={row.get('emoji','?')} alias={row.get('alias_file','')}")
PY
    ;;
  slot)
    if [[ $# -lt 2 ]]; then
      usage
      exit 1
    fi
    slot="$2"
    python3 - "$INDEX_FILE" "$slot" <<'PY'
import json, sys
path, slot = sys.argv[1], sys.argv[2]
data = json.load(open(path, encoding="utf-8"))
row = data.get("slots", {}).get(str(slot), {})
if not row:
    print(f"No alias metadata for slot {slot}")
    raise SystemExit(1)
print(json.dumps(row, ensure_ascii=False, indent=2))
PY
    ;;
  sidecar)
    if [[ $# -lt 2 ]]; then
      usage
      exit 1
    fi
    slot="$2"
    sidecar=$(python3 - "$INDEX_FILE" "$slot" <<'PY'
import json, sys
path, slot = sys.argv[1], sys.argv[2]
data = json.load(open(path, encoding="utf-8"))
row = data.get("slots", {}).get(str(slot), {})
print(row.get("sidecar_path", ""))
PY
)
    if [[ "${sidecar}" == user://saves/* ]]; then
      sidecar="${SAVE_DIR}/$(basename "${sidecar}")"
    fi
    if [[ -z "${sidecar}" || ! -f "${sidecar}" ]]; then
      echo "No sidecar found for slot ${slot}"
      exit 1
    fi
    cat "${sidecar}"
    ;;
  files)
    ls -1 "${SAVE_DIR}"/save_slot_*_*.tres 2>/dev/null || echo "No emoji alias save files found."
    ;;
  *)
    usage
    exit 1
    ;;
esac
