class_name EmojiRegistry
extends RefCounted

## Single source of truth for emoji → SVG texture.
##
## Three-tier fallback (in order):
##   1. Custom SVGs  — hand-crafted art in Assets/UI/
##   2. Twemoji SVGs — downloaded vectors in Assets/emoji_svg/
##   3. Text         — caller renders as Unicode glyph (null returned)
##
## Data lives in Assets/emoji_registry.json (generated by sync_emoji_pipeline.py).
## Loaded once at boot; JSON is inert at runtime.
##
## Use EmojiRegistry.shared() to get the singleton instance.

const REGISTRY_PATH = "res://Assets/emoji_registry.json"

static var _instance = null

static func shared() -> EmojiRegistry:
	if not _instance:
		_instance = EmojiRegistry.new()
	return _instance


var _custom:  Dictionary = {}  # tier 1: normalized emoji → res://Assets/UI/...
var _twemoji: Dictionary = {}  # tier 2: normalized emoji → res://Assets/emoji_svg/...
var _cache:   Dictionary = {}  # normalized emoji → loaded Texture2D
var _warned:  Dictionary = {}  # normalized emoji → true (warn once per session)


func _init() -> void:
	# One JSON-load authority (slop knot #7); the registry is REQUIRED — missing
	# or malformed is loud (push_error), exactly as before.
	var res: Dictionary = preload("res://Core/Config/JsonFileLoader.gd").load_json(
		REGISTRY_PATH, {"context": "EmojiRegistry", "required": true, "root": "dictionary"})
	if not res.ok:
		return
	_custom  = res.data.get("custom",  {})
	_twemoji = res.data.get("twemoji", {})


func get_texture(emoji: String) -> Texture2D:
	var k := _norm(emoji)
	if k in _cache:
		return _cache[k]
	# Tier 1 — custom SVG
	if k in _custom:
		var t: Texture2D = ResourceLoader.load(_custom[k])
		if t:
			_cache[k] = t
			return t
	# Tier 2 — twemoji SVG
	if k in _twemoji:
		var t: Texture2D = ResourceLoader.load(_twemoji[k])
		if t:
			_cache[k] = t
			return t
	# Tier 3 — text fallback (caller handles)
	if k not in _warned:
		_warned[k] = true
		push_warning("EmojiRegistry: no SVG for '%s' — text fallback" % emoji)
	return null


func has_texture(emoji: String) -> bool:
	var k := _norm(emoji)
	return k in _custom or k in _twemoji


func print_statistics() -> void:
	print("EmojiRegistry: %d cached, %d text fallbacks" % [_cache.size(), _warned.size()])


func _norm(s: String) -> String:
	return EmojiUtil.normalize(s)
