#!/bin/bash
## Play Test: Network Overlay and Tomato Visuals
## This script provides instructions for manual play testing

echo "═══════════════════════════════════════════════════════"
echo "   PLAY TEST: Conspiracy Network & Tomato Visuals"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "This is a manual play test. Follow these steps:"
echo ""
echo "STEP 1: Launch the game"
echo "  cd /home/tehcr33d/ws/SpaceWheat"
echo "  godot scenes/FarmView.tscn"
echo ""
echo "STEP 2: Test Network Overlay Toggle (N key)"
echo "  Expected: Press N → Network overlay appears"
echo "  Expected: See 12 nodes with emoji labels"
echo "  Expected: Nodes connected by lines"
echo "  Expected: Press N again → Network disappears"
echo ""
echo "STEP 3: Test Force-Directed Graph"
echo "  Expected: Nodes move and settle into stable layout"
echo "  Expected: Nodes don't overlap"
echo "  Expected: Layout stabilizes within 2-3 seconds"
echo ""
echo "STEP 4: Plant Tomatoes (T key)"
echo "  Action: Select empty plot, press T"
echo "  Expected: Tomato planted (costs 5 credits)"
echo "  Expected: Tomato appears with 🍅 emoji"
echo "  Expected: Growth bar appears"
echo ""
echo "STEP 5: Watch Tomato Visuals Update"
echo "  Expected: Tomato color changes (blue → white → red)"
echo "  Expected: Tomato pulses/glows"
echo "  Expected: Size changes slightly"
echo "  Expected: Visuals update in real-time"
echo ""
echo "STEP 6: Check Network with Tomatoes"
echo "  Action: Press N while tomatoes growing"
echo "  Expected: See which node tomato is connected to"
echo "  Expected: Node energy changes affect tomato color"
echo "  Expected: Connection lines show energy flow"
echo ""
echo "STEP 7: Plant Multiple Tomatoes"
echo "  Action: Plant 3-5 tomatoes in different plots"
echo "  Expected: Each assigned to different conspiracy node"
echo "  Expected: Different tomatoes have different colors"
echo "  Expected: Tomatoes update independently"
echo ""
echo "STEP 8: Watch Conspiracy Activation"
echo "  Expected: Console shows conspiracy activation messages"
echo "  Expected: Network nodes glow brighter when active"
echo "  Expected: Tomato size increases when conspiracies active"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "To run automated initialization test:"
echo "  ./tests/playtest_network_tomatoes_auto.sh"
echo ""
